### ISSUE TITLE
Manus requires Visual studio 2015

### ISSUE THREAD

**Issue by GitHubJasper** [ManusVR/Manus#13]
Visual Studio 2015 needs to be installed since it depends on some of those dll's.

A fix for this:
1) open Visual Studio DLL project.
2) Go to project properties; 
3) Go to Configuration Properties->C\C++ -> Code Generation.
4) In the list find the item "Runtime Library". Then change it to be "Multi-Threaded (\MT)"..
5) reCompile your library....

Second last comment from (http://forum.unity3d.com/threads/fallback-handler-could-not-load-library-unity-4-2-osx-10-8-4-standalone.191966/)

**Comment by Armada651** [comment]
We're already aware of this, you need to install the Visual C++ 2015 Redistributable. You don't need the entire Visual Studio. This is very standard and most applications that are compiled for Visual C++ 2015 install this library automatically.

In the next version we'll statically link to the runtime.
